# Generated by Django 5.0.1 on 2024-01-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movielist_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genere',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=255),
        ),
    ]
